site_name: UnrealCV
theme: readthedocs
pages:
    - Home: index.md
    - "Use a game binary":
        - "Getting started": binary/getting-started.md
        - "Release a binary": binary/new-binary.md
    - "Use the UE4 plugin":
        - "Installation": plugin/install.md
        - "Usage": plugin/usage.md
    - Development:
        - "Environment setup": dev/setup.md
        - "Example: add a new command": dev/example-add-new-command.md
    - Reference:
        - Architecture: ref/arch.md
        - "UnrealCV commands": ref/command.md
    - FAQ: faq.md
